services:
  gateway:
    build:
      context: .
      dockerfile: /apps/gateway/Dockerfile
      target: developer
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 80:80
    develop:
      watch:
        - action: sync+restart
          path: ./.env
          target: /app/.env

        - action: rebuild
          path: package.json
    command: pnpm start:dev gateway
  telegram:
    build:
      context: .
      dockerfile: /apps/telegram/Dockerfile
      target: developer
    volumes:
      - .:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync+restart
          path: ./.env
          target: /app/.env

        - action: rebuild
          path: package.json
    command: pnpm start:dev telegram
  queue:
    image: rabbitmq
    ports:
      - 5672:5672
