name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Notify via Telegram
        if: success()
        run: |
          MESSAGE="✅ Deploy завершён успешно 🎉%0A\
          Проект: ${{ github.repository }}%0A\
          Ветка: ${{ github.ref }}%0A\
          Коммит: ${{ github.sha }}%0A\
          Автор: ${{ github.actor }}"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="$MESSAGE"
